src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Activity_Report_Active__c</fullName>
        <formula>(ISBLANK(Activity_Report_Start__c) &amp;&amp; ISBLANK(Activity_Report_End__c))
||
(Activity_Report_Start__c &lt;= TODAY() &amp;&amp; Activity_Report_End__c &gt;= TODAY())</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Activity Report Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>EC_Activity_Report_Emails__c</fullName>
        <label>EC Activity Report Emails</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>EC_Activity_Report_Midweek__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Send report midweek rather than Friday</inlineHelpText>
        <label>EC Activity Report Midweek</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/ScheduledECActivityReport.cls
public class ScheduledECActivityReport  implements Schedulable
{
    public void execute(SchedulableContext sc)
    {
        for(Account a : [SELECT ID
                        FROM    Account
                        WHERE   EC_Activity_Report_Emails__c != null AND
                                EC_Activity_Report_Midweek__c = false AND
                                Activity_Report_Active__c = true])
        {
            BPReports.sendECActivityReport(a.ID, Date.today().toStartOfWeek().addDays(1), Date.today(), true);
        }
    }
}