src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>BrokeredLive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>BrokeredLive</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Job_Seeker__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Job Seekers</relationshipLabel>
        <relationshipName>Job_Seekers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>BrokeredLive_Phrase_Prompt__c</fullName>
        <inlineHelpText>Pick a question to prompt the jobseeker for their password</inlineHelpText>
        <label>Password Prompt</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>What is your favourite food</fullName>
                </value>
                <value>
                    <fullName>Who is your favourite movie star</fullName>
                </value>
                <value>
                    <fullName>Who was you favourite teacher at school</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>BrokeredLive_Phrase__c</fullName>
        <label>BrokeredLive Password</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BrokeredLive_Username__c</fullName>
        <externalId>true</externalId>
        <label>BrokeredLive Username</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>BrokeredLive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>BrokeredLive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>X1_Marketable_Attribute__c</fullName>
        <label>1  Marketable Attribute</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>X2_Marketable_Attribute__c</fullName>
        <label>2 Marketable Attribute</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>X3_Marketable_Attribute__c</fullName>
        <label>3 Marketable Attribute</label>
        <type>TextArea</type>
    </fields>
    <label>Job Seeker</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Seekers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Live_Session__c.object
<CustomObject>
    <fields>
        <fullName>Job_Seeker__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Job Seeker</label>
        <referenceTo>Job_Seeker__c</referenceTo>
        <relationshipLabel>Live Sessions</relationshipLabel>
        <relationshipName>Live_Sessions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>X1_Marketable_Attribute__c</fullName>
        <label>1 Marketable Attribute</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>X2_Marketable_Attribute__c</fullName>
        <label>2 Marketable Attribute</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>X3_Marketable_Attribute__c</fullName>
        <label>3 Marketable Attribute</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Live Session</label>
    <nameField>
        <displayFormat>LS{000000}</displayFormat>
        <label>Live Session Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Live Sessions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/BLLoginController.cls
public with sharing class BLLoginController 
	extends BPPageBase
{
    public BLLoginController() 
    {

    }

    public String Username
    {
    	get;
    	set;
    }

    public String Passphrase
    {
    	get;
    	set;
    }

    public String PhraseQuestion
    {
    	get;
    	set;
    }

    public void getPhrase()
    {

    	Job_Seeker__c js = getJobseeker();
    	PhraseQuestion = js.BrokeredLive_Phrase_Prompt__c;
    	if(String.isBlank(js.BrokeredLive_Phrase__c))
    	{
    		addMessage('Login not found.');
    	}
    }

    public PageReference login()
    {
        try
        {
        	Job_Seeker__c js = getJobseeker();
        	if(Passphrase == js.BrokeredLive_Phrase__c)
        	{
        		Live_Session__c ls = new Live_Session__c();
        		ls.Job_Seeker__c = js.ID;
        		ls.X1_Marketable_Attribute__c = js.X1_Marketable_Attribute__c;
        		ls.X2_Marketable_Attribute__c = js.X2_Marketable_Attribute__c;
        		ls.X3_Marketable_Attribute__c = js.X3_Marketable_Attribute__c;
        		insert ls;

        		PageReference pg = Page.BLAttributes;
        		pg.getParameters().put('sessId', ls.ID);
        		pg.getParameters().put('chkId', ls.Job_Seeker__c);
        		return pg;
        	}
        	return null;
        }
        catch(Exception ex)
        {
            return addMessage(ex);
        }
    }

    private Job_Seeker__c getJobseeker()
    {
        if(String.isNotBlank(Username))
        {
        	for(Job_Seeker__c js :[SELECT 	ID,
        									X1_Marketable_Attribute__c,
        									X2_Marketable_Attribute__c,
        									X3_Marketable_Attribute__c,
        									BrokeredLive_Phrase__c,
        									BrokeredLive_Phrase_Prompt__c
        							FROM 	Job_Seeker__c
        							WHERE 	BrokeredLive__c = true AND
                                            BrokeredLive_Username__c = :Username AND
											Account__r.BrokeredLive__c = true])
        	{
        		return js;
        	}
        }
    	return new Job_Seeker__c();
    }
}