src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>BrokeredLive_Per_EC__c</fullName>
        <label>BrokeredLive Per EC</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>BrokeredLive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>BrokeredLive</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Communication__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Communications</relationshipLabel>
        <relationshipName>Communications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Job_Seeker__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Job Seeker</label>
        <referenceTo>Job_Seeker__c</referenceTo>
        <relationshipLabel>Communications</relationshipLabel>
        <relationshipName>Communications</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Communication</label>
    <nameField>
        <displayFormat>C{00000}</displayFormat>
        <label>Communication Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Communications</pluralLabel>
    <recordTypes>
        <fullName>Email</fullName>
        <active>true</active>
        <label>Email</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Employer_Contact__c.object
<CustomObject>
    <fields>
        <fullName>Job_Seeker__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Job Seeker</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Job_Seeker__c.Assigned_To__c</field>
                <operation>equals</operation>
                <valueField>$User.Id</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Job_Seeker__c</referenceTo>
        <relationshipLabel>Employer Contacts</relationshipLabel>
        <relationshipName>Employer_Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Employer Contact</label>
    <nameField>
        <displayFormat>EC{000000000}</displayFormat>
        <label>Employer Contact ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Employer Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Follow_Up__c.object
<CustomObject>
    <fields>
        <fullName>Action_Taken__c</fullName>
        <label>Action Taken</label>
        <picklist>
            <picklistValues>
                <fullName>Interview</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Resume drop off</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No answer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Left message</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No vacancy - Decision maker</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vacancy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Resume sent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sent another jobseeker</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wage subsidy details sent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Work trial organised</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Do not disturb</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Call back</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wage subsidy signed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Actioned__c</fullName>
        <label>Actioned</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Assigned_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assigned To</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Follow_Ups</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <formula>Employer_Contact__r.Contact_Email__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Email</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Employer_Contact__c</fullName>
        <label>Employer Contact</label>
        <referenceTo>Employer_Contact__c</referenceTo>
        <relationshipLabel>Follow Ups</relationshipLabel>
        <relationshipName>Follow_Ups</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Job_Seeker__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Job Seeker</label>
        <referenceTo>Job_Seeker__c</referenceTo>
        <relationshipLabel>Follow Ups</relationshipLabel>
        <relationshipName>Follow_Ups</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Follow Up</label>
    <nameField>
        <displayFormat>FU{0000000000}</displayFormat>
        <label>Follow Up ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Follow Ups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Job_Seeker__c.object
<CustomObject>
    <fields>
        <fullName>Account_Name__c</fullName>
        <label>Account Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Job Seekers</relationshipLabel>
        <relationshipName>Job_Seekers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Address_Location__c</fullName>
        <formula>Suburb__c + &apos; &apos; + TEXT(State__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Address Location</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Assigned_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assigned To</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Job_Seekers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BrokeredLive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>BrokeredLive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Marketing_Ended__c</fullName>
        <label>Marketing Ended</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Marketing_Outcome__c</fullName>
        <label>Marketing Outcome</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Placed</fullName>
                </value>
                <value>
                    <fullName>Found own employment</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Marketing_Started__c</fullName>
        <label>Marketing Started</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Placed_Date__c</fullName>
        <label>Placed Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Placed_With__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Placed With</label>
        <referenceTo>Business__c</referenceTo>
        <relationshipLabel>Job Seekers</relationshipLabel>
        <relationshipName>Job_Seekers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Professional_and_Specialist_Role__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Professional and Specialist Role</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Qualifications__c</fullName>
        <label>Qualifications</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>First Aid</fullName>
                </value>
                <value>
                    <fullName>Certificate (1, 2 or 3)</fullName>
                </value>
                <value>
                    <fullName>Forklift</fullName>
                </value>
                <value>
                    <fullName>White Card</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>ACT</fullName>
                </value>
                <value>
                    <fullName>NSW</fullName>
                </value>
                <value>
                    <fullName>NT</fullName>
                </value>
                <value>
                    <fullName>QLD</fullName>
                </value>
                <value>
                    <fullName>SA</fullName>
                </value>
                <value>
                    <fullName>TAS</fullName>
                </value>
                <value>
                    <fullName>VIC</fullName>
                </value>
                <value>
                    <fullName>WA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Suburb__c</fullName>
        <label>Suburb</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>X1_Marketable_Attribute__c</fullName>
        <label>1  Marketable Attribute</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>X2_Marketable_Attribute__c</fullName>
        <label>2 Marketable Attribute</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>X3_Marketable_Attribute__c</fullName>
        <label>3 Marketable Attribute</label>
        <type>TextArea</type>
    </fields>
    <label>Job Seeker</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Seekers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Live_Session__c.object
<CustomObject>
    <fields>
        <fullName>Job_Seeker__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Job Seeker</label>
        <referenceTo>Job_Seeker__c</referenceTo>
        <relationshipLabel>Live Sessions</relationshipLabel>
        <relationshipName>Live_Sessions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>X1_Marketable_Attribute__c</fullName>
        <label>1 Marketable Attribute</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>X2_Marketable_Attribute__c</fullName>
        <label>2 Marketable Attribute</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>X3_Marketable_Attribute__c</fullName>
        <label>3 Marketable Attribute</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Live Session</label>
    <nameField>
        <displayFormat>LS{000000}</displayFormat>
        <label>Live Session Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Live Sessions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Account_Name__c</fullName>
        <formula>Contact.Account.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BrokeredLive_Per_EC__c</fullName>
        <formula>Contact.Account.BrokeredLive_Per_EC__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>BrokeredLive Per EC</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>BrokeredLive__c</fullName>
        <formula>Contact.Account.BrokeredLive__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>BrokeredLive</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/BPPageBase.cls
public virtual with sharing class BPPageBase 
{
    public BPPageBase()
    {
        setComaptibility();
    }

    public BPPageBase(ApexPages.StandardController c)
    {
        setComaptibility();
    }

    public Boolean testErrorEnabled = false;
    
    protected ID jobSeekerID;

    private transient User tCurrentUser;
    private transient Job_Seeker__c tJobSeeker;
    private transient List<SelectOption> tConsultants;
    private transient List<User> tSiteUsers;
    private transient Map<String, Schema.RecordTypeInfo> tCommunicationRecordTypesByName;
    private transient Live_Session__c tSession;

    public BPPageBase ThisController
    {
        get 
        {
            return this;
        }
    }
    public String MobileNumber
    {
        get
        {
            return getMobileNumber(JobSeeker);
        }
        set
        {
            setMobileNumber(JobSeeker, value);
        }
    }

    public String Interview
    {
        get
        {
            return BPConstants.EmployerContact_Result_Interview;
        }
    }

    public String ResumeDropOff
    {
        get
        {
            return BPConstants.EmployerContact_Result_ResumeDropOff;
        }
    }

    public String CallBack
    {
        get
        {
            return BPConstants.EmployerContact_Result_Callback;
        }
    }
    
    public void throwTestError()
    {
        if(testErrorEnabled)
        {
            Integer i = 0;
            i = 1 / i;
        }
    }

    public Live_Session__c LiveSession 
    {
        get
        {
            if(tSession == null)
            {
                tSession = getLiveSession();
            }
            return tSession;
        }
    }
    
    public User CurrentUser
    {
        get
        {
            if(tCurrentUser == null)
            {
                tCurrentUser = [SELECT Id, 
                                        Name, 
                                        Username, 
                                        LastName, 
                                        FirstName, 
                                        Title, 
                                        Email, 
                                        Alias, 
                                        Phone,
                                        MobilePhone,
                                        IsActive,                                         
                                        UserType, 
                                        ProfileId,
                                        Profile.Name,
                                        ContactId, 
                                        Contact.AccountID,
                                        AccountId,
                                        Contact.Account.Name,
                                        Account_Name__c,
                                        BrokeredLive__c,
                                        BrokeredLive_Per_EC__c,
                                        UserRoleID
                                FROM    User
                                WHERE   ID = :UserInfo.getUserId()];
            }
            return tCurrentUser;
        }
    }

    public Job_Seeker__c JobSeeker
    {
        get 
        {       
            if(tJobSeeker == null)
            {
                tJobSeeker = new Job_Seeker__c();
                for(Job_Seeker__c js : [SELECT Id, 
                                                Name, 
                                                Account__c, 
                                                Address_Location__c, 
                                                Assigned_To__c, 
                                                Email__c, 
                                                Marketing_Ended__c, 
                                                Marketing_Outcome__c, 
                                                Marketing_Started__c,
                                                Professional_and_Specialist_Role__c, 
                                                Qualifications__c, 
                                                State__c, 
                                                Suburb__c, 
                                                X1_Marketable_Attribute__c, 
                                                X2_Marketable_Attribute__c,
                                                X3_Marketable_Attribute__c, 
                                                Account_Name__c,
                                                Placed_Date__c
                                        FROM    Job_Seeker__c
                                        WHERE   ID = :jobSeekerID])
                {
                    tJobSeeker = js;
                }
            }
            return tJobSeeker;
        }
    }

    public Boolean IsManager
    {
        get
        {
            return CurrentUser.Profile.Name == BPConstants.Profile_BPlusManager || IsAdmin;
        }
    }

    public Boolean IsAdmin
    {
        get
        {
            return CurrentUser.Profile.Name == BPConstants.Profile_SystemAdministrator;
        }
    }

    public List<SelectOption> Consultants
    {
        get 
        {
            if(tConsultants == null)
            {
                tConsultants = getSelectListFromObjectList(SiteUsers);
            }
            return tConsultants;
        }
    }

    public List<User> SiteUsers
    {
        get 
        {
            if(tSiteUsers == null)
            {
                tSiteUsers = [SELECT    ID, 
                                        Name 
                                FROM    User
                                WHERE   IsActive = true AND 
                                        IsPortalEnabled = true //AND 
                                        //UserRoleID = :CurrentUser.UserRoleID
                                ORDER BY Name];
            }
            return tSiteUsers;
        }
    }

    public Map<String, Schema.RecordTypeInfo> CommunicationRecordTypesByName
    {
        get
        {
            if(tCommunicationRecordTypesByName == null)
            {
                tCommunicationRecordTypesByName = Schema.SObjectType.Communication__c.getRecordTypeInfosByName();
            }
            return tCommunicationRecordTypesByName;
        }
    }

    public Boolean IsSandbox
    {
        get
        {
            return URL.getSalesforceBaseUrl().getHost().contains('.cs5.');
        }
    }

    public Date PlacedDate
    {
        get;
        set;
    }

    public PageReference placedJobSeeker()
    {
        Savepoint sp = Database.setSavepoint();
        try
        {
            if(JobSeeker.Placed_Date__c == null)
            {
                addMessage('Placed date is required.');
                return null;
            }
            String empId = getParameter('empId');
            String fuId = getParameter('fuId');
            String ecId = getParameter('ecId');
            JobSeeker.Placed_With__c = empId;
            update JobSeeker;
            
            PageReference pg;
            Employer_Contact__c ec;
            if(String.isNotBlank(ecId))
            {
                ec = [SELECT ID,
                            (SELECT ID 
                            FROM    Follow_Ups__r 
                            WHERE   Actioned__c = null) 
                    FROM    Employer_Contact__c 
                    WHERE   ID = :ecId];
                pg = new PageReference('/' + ecId);
            }
            else if (String.isNotBlank(fuId))
            {
                ec = [SELECT ID,
                            (SELECT ID 
                            FROM    Follow_Ups__r 
                            WHERE   ID = :fuId) 
                    FROM    Employer_Contact__c 
                    WHERE   ID IN (SELECT Employer_Contact__c 
                                    FROM  Follow_Up__c 
                                    WHERE   ID = :fuId)];
                pg = new PageReference('/' + fuId);
            }
            for(Follow_Up__c fu : ec.Follow_Ups__r)
            {
                fu.Action_Taken__c = BPConstants.FollowUp_Type_Placed;
                fu.Actioned__c = DateTime.now();
            }
            update ec.Follow_Ups__r;
            //addMessage(ApexPages.Severity.INFO, 'Jobseeker updated.');
            return pg;
        }
        catch(Exception ex)
        {
            return addMessage(ex, sp);
        }
    }
    
    protected PageReference addMessage(String s)
    {
        ApexPages.addMessage(new ApexPages.Message(ApexPages.severity.ERROR, s));
        return null;
    }

    protected PageReference addMessage(Exception ex)
    {
    	addMessage(ApexPages.Severity.ERROR, ex.getMessage() + (IsSandbox ? ('\n' + ex.getStackTraceString()) : ''));
        return null;
    }

    protected PageReference addMessage(Exception ex, Savepoint sp)
    {
        addMessage(ex);
        if(sp != null)
        {
            Database.rollback(sp);
        }
        return null;
    }

    protected PageReference addMessage(ApexPages.Severity importance, String s)
    {
        ApexPages.addMessage(new ApexPages.Message(importance, s));
        return null;
    }
    
    protected String getParameter(String parameterName)
    {
    	if(ApexPages.currentPage() == null)
    	{
    		return null;
    	}
        return ApexPages.currentPage().getParameters().get(parameterName);
    }

    protected List<SelectOption> getSelectListFromObjectList(List<sObject> sObjects)
    {
        return getSelectListFromObjectList(sObjects, 'ID', 'Name', true);
    }

    protected List<SelectOption> getSelectListFromObjectList(List<sObject> sObjects, Boolean addNoneOption)
    {
        return getSelectListFromObjectList(sObjects, 'ID', 'Name', addNoneOption);
    }

    protected List<SelectOption> getSelectListFromObjectList(List<sObject> sObjects, String fieldForID, String fieldForLabel)
    {
        return getSelectListFromObjectList(sObjects, fieldForID, fieldForLabel, true);
    }

    protected List<SelectOption> getSelectListFromObjectList(List<sObject> sObjects, String fieldForID, String fieldForLabel, Boolean addNoneOption)
    {
        List<SelectOption> optionList = new List<SelectOption>();
        if(addNoneOption)
        {
            optionList.add(new SelectOption('',  '--None--'));
        }
        for(sObject obj : sObjects)
        {
            String idValue = (String)obj.get(fieldForID);
            String labelValue = (String)obj.get(fieldForLabel);
            optionList.add(new SelectOption(idValue, labelValue));
        }
        return optionList;
    }

    protected List<SelectOption> getSelectListFromPicklistField(sObjectField fieldToken, Boolean addNoneOption)
    {
        List<SelectOption> optionList = new List<SelectOption>();
        if(addNoneOption)
        {
            optionList.add(new SelectOption('',  '--None--'));
        }
        DescribeFieldresult result = fieldToken.getDescribe();
        for(PicklistEntry ple : result.getPicklistValues())
        {
            optionList.add(new SelectOption(ple.getValue(), ple.getLabel()));
        }
        return optionList;
    }

    protected Boolean isRequiredFieldValid(object val, String fieldName, Boolean wasPreviouslyValid)
    {
        return isRequiredFieldValid(val, fieldName, null, wasPreviouslyValid, true);
    }

    protected Boolean isRequiredFieldValid(object val, String fieldName, String msgSuffix, Boolean wasPreviouslyValid, Boolean displayMessage)
    {
        if(val == null || val == '')
        {
            if(displayMessage)
            {
                getRequiredFieldMessage(fieldName, msgSuffix);
            }
            return false;
        }
        return wasPreviouslyValid ? true : wasPreviouslyValid;
    }

    protected void getRequiredFieldMessage(String fieldName, String msgSuffix)
    {
        addMessage(fieldName + ' is required' + (msgSuffix == null ? '.' : msgSuffix + '.'));
    }

    protected Boolean validateMobileNumber(String s)
    {
        return validateMobileNumber(s, true);
    }

    protected Boolean validateMobileNumber(String s, Boolean throwException)
    {
        if(String.isBlank(s))
        {
            if(throwException)
            {
                throw new BPException('Mobile phome number is required');
            }
            return false;
        }
        if(BPSMSUtilities.cleanPhoneNumber(s, throwException) == null)
        {
            return false;
        }
        return true;
    }

    protected Live_Session__c getLiveSession()
    {
        String sessID = getParameter('sessId');
        String chkId = getParameter('chkId');
        for(Live_Session__c ls : [SELECT    ID,
                                            Job_Seeker__c,
                                            Job_Seeker__r.Name,
                                            Job_Seeker__r.Address_Location__c,
                                            Job_Seeker__r.Account__c,
                                            X1_Marketable_Attribute__c,
                                            X2_Marketable_Attribute__c,
                                            X3_Marketable_Attribute__c
                                    FROM    Live_Session__c 
                                    WHERE   ID = :sessID AND 
                                            Job_Seeker__c = :chkId])
        {
            return ls;
        }
        return new Live_Session__c();
    }

    protected String getMobileNumber(Job_Seeker__c js)
    {
        Map<String, String> numbersByJskId = Test.isRunningTest() ? null : (Map<String, String>)Cache.Session.get('local.UserSession.mobileNumber');
        if(numbersByJskId == null)
        {
            numbersByJskId = new Map<String, String>();
        }
        return Test.isRunningTest() ? '0404240508' : numbersByJskId.get(js.ID);
    }

    protected void setMobileNumber(Job_Seeker__c js, String num)
    {
        Map<String, String> numbersByJskId = Test.isRunningTest() ? null : (Map<String, String>)Cache.Session.get('local.UserSession.mobileNumber');
        if(numbersByJskId == null)
        {
            numbersByJskId = new Map<String, String>();
        }
        if(js.ID != null) 
        {    
            numbersByJskId.put(js.ID, num);
        }
        if(!Test.isRunningTest())
        {
            Cache.Session.put('local.UserSession.mobileNumber', numbersByJskId);
        }
    }

    public void rerenderPage()
    {}

    private void setComaptibility()
    {
        if(ApexPages.currentPage() != null)
        {
            ApexPages.currentPage().getHeaders().put('X-UA-Compatible', 'IE=Edge');
        }
    }
}