src/objects/Business__c.object
<CustomObject>
    <label>Business</label>
    <nameField>
        <label>Business Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Businesses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Employer_Contact__c.object
<CustomObject>
    <fields>
        <fullName>Business__c</fullName>
        <label>Business</label>
        <referenceTo>Business__c</referenceTo>
        <relationshipLabel>Employer Contacts</relationshipLabel>
        <relationshipName>Employer_Contacts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Job_Seeker__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Job Seeker</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Job_Seeker__c.Assigned_To__c</field>
                <operation>equals</operation>
                <valueField>$User.Id</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Job_Seeker__c</referenceTo>
        <relationshipLabel>Employer Contacts</relationshipLabel>
        <relationshipName>Employer_Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Employer Contact</label>
    <nameField>
        <displayFormat>EC{000000000}</displayFormat>
        <label>Employer Contact ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Employer Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Follow_Up__c.object
<CustomObject>
    <fields>
        <fullName>Employer_Contact__c</fullName>
        <label>Employer Contact</label>
        <referenceTo>Employer_Contact__c</referenceTo>
        <relationshipLabel>Follow Ups</relationshipLabel>
        <relationshipName>Follow_Ups</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Job_Seeker__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Job Seeker</label>
        <referenceTo>Job_Seeker__c</referenceTo>
        <relationshipLabel>Follow Ups</relationshipLabel>
        <relationshipName>Follow_Ups</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Follow Up</label>
    <nameField>
        <displayFormat>FU{0000000000}</displayFormat>
        <label>Follow Up ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Follow Ups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Job_Seeker__c.object
<CustomObject>
    <label>Job Seeker</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Seekers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TestBPEmployerExtension.cls
@isTest
private class TestBPEmployerExtension 
{
	private static testMethod void test1()
	{
		Job_Seeker__c js = TestJobSeekerExtension.insertJobSeeker();
		Employer_Contact__c ec = TestJobSeekerExtension.insertEmployerContact(js);
		Follow_Up__c fu = TestJobSeekerExtension.insertFollowup(ec);
		Business__c b = [SELECT ID FROM Business__c WHERE ID = :ec.Business__c];

		BPEmployerExtension ext = new BPEmployerExtension(new ApexPages.StandardController(b));

		system.assert(ext.EmployerContacts != null);
		system.assert(ext.Followups != null);
		system.assert(ext.Subsidies != null);

		ext.newContact();
	}
}