src/objects/Business__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Businesses</relationshipLabel>
        <relationshipName>Businesses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <label>Business</label>
    <nameField>
        <label>Business Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Businesses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Business__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Business</label>
        <referenceTo>Business__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Employer_Contact__c.object
<CustomObject>
    <fields>
        <fullName>Business__c</fullName>
        <label>Business</label>
        <referenceTo>Business__c</referenceTo>
        <relationshipLabel>Employer Contacts</relationshipLabel>
        <relationshipName>Employer_Contacts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Contact_Email__c</fullName>
        <label>Contact Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Contact_Number__c</fullName>
        <label>Contact Number</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Contacted_On__c</fullName>
        <label>Contacted On</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Job_Seeker__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Job Seeker</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Job_Seeker__c.Assigned_To__c</field>
                <operation>equals</operation>
                <valueField>$User.Id</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Job_Seeker__c</referenceTo>
        <relationshipLabel>Employer Contacts</relationshipLabel>
        <relationshipName>Employer_Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>EC</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Employer_Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Employer Contact</label>
    <nameField>
        <displayFormat>EC{000000000}</displayFormat>
        <label>Employer Contact ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Employer Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Follow_Up__c.object
<CustomObject>
    <fields>
        <fullName>Actioned__c</fullName>
        <label>Actioned</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Assigned_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assigned To</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Follow_Ups</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact_Number__c</fullName>
        <formula>Employer_Contact__r.Contact_Number__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Contact Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Due_Date__c</fullName>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <formula>Employer_Contact__r.Contact_Email__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Email</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Employer_Contact__c</fullName>
        <label>Employer Contact</label>
        <referenceTo>Employer_Contact__c</referenceTo>
        <relationshipLabel>Follow Ups</relationshipLabel>
        <relationshipName>Follow_Ups</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Employer__c</fullName>
        <formula>Employer_Contact__r.Business__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Employer</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Job_Seeker__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Job Seeker</label>
        <referenceTo>Job_Seeker__c</referenceTo>
        <relationshipLabel>Follow Ups</relationshipLabel>
        <relationshipName>Follow_Ups</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Repeat Call</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Call back</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Resume</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Interview</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Employer Meeting</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Follow Up</label>
    <nameField>
        <displayFormat>FU{0000000000}</displayFormat>
        <label>Follow Up ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Follow Ups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Job_Seeker__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Job Seekers</relationshipLabel>
        <relationshipName>Job_Seekers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Assigned_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assigned To</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Job_Seekers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Marketing_Ended__c</fullName>
        <label>Marketing Ended</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Marketing_Started__c</fullName>
        <label>Marketing Started</label>
        <type>DateTime</type>
    </fields>
    <label>Job Seeker</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Seekers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/BPHomeController.cls
public with sharing class BPHomeController 
	extends BPPageBase
{
	public BPHomeController()
	{
	}

	transient List<Job_Seeker__c> tMyJobSeekers;
	transient List<Follow_Up__c> tMyFollowUps;
	transient List<Employer_Contact__c> tMyEmployerContacts;
	transient List<Job_Seeker__c> tJobSeekerSearchResults;

	
	public String JobSeekerSearch
	{
		get;
		set;
	}

	public List<Job_Seeker__c> MyJobSeekers
	{
		get
		{
			if(tMyJobSeekers == null)
			{
				tMyJobSeekers = [SELECT ID,
										Name,
										Mobile__c,
										Email__c,
										JSK_ID__c,
										Marketing_Started__c,
										Assigned_To__c
								FROM 	Job_Seeker__c
								WHERE 	Assigned_To__c = :UserInfo.getUserId() AND 
										Marketing_Ended__c = null];
			}
			return tMyJobSeekers;
		}
	}

	public List<Job_Seeker__c> JobSeekerSearchResults
	{
		get
		{
			if(tJobSeekerSearchResults == null)
			{
				tJobSeekerSearchResults = new List<Job_Seeker__c>();
			}
			return tJobSeekerSearchResults;
		}
	}

	public List<Follow_Up__c> MyFollowUps
	{
		get
		{
			if(tMyFollowUps == null)
			{
				tMyFollowUps = [SELECT ID,
										Name,
										Due_Date__c,
										Job_Seeker__c,
										Employer__c,
										Type__c,
										Employer_Contact__c,
										Contact_Number__c,
										Email__c,
										Employer_Contact__r.Meeting_Time__c,
										Job_Seeker__r.Name
								FROM 	Follow_Up__c
								WHERE 	(Employer_Contact__r.User__c = :UserInfo.getUserId() OR
										Assigned_To__c = :UserInfo.getUserId()) AND 
										Actioned__c = null AND
										DAY_ONLY(Due_Date__c) <= :Date.today()
								ORDER BY Due_Date__c];
			}
			return tMyFollowUps;
		}
	}

	public List<Employer_Contact__c> MyEmployerContacts
	{
		get
		{
			if(tMyEmployerContacts == null)
			{
				tMyEmployerContacts = [SELECT ID,
												Name,
												Contacted_On__c,
												Contact_Email__c,
												Contact_Number__c,
												Job_Seeker__c,
												Job_Seeker__r.Name,
												Job_Seeker__r.Marketing_Started__c,
												Business__r.Name
										FROM 	Employer_Contact__c
										WHERE 	User__c = :UserInfo.getUserId() 
										ORDER BY Contacted_On__c DESC];
			}
			return tMyEmployerContacts;
		}
	}

	public PageReference searchJS()
	{
		try
		{
			tJobSeekerSearchResults = [SELECT ID,
											Name,
											Mobile__c,
											Email__c,
											JSK_ID__c,
											Marketing_Started__c,
											Marketing_Ended__c,
											Assigned_to__c
									FROM 	Job_Seeker__c
									WHERE 	Account__c = :CurrentUser.Contact.AccountID AND 
											(
												Name LIKE :('%' + JobSeekerSearch + '%') OR
												JSK_ID__c LIKE :('%' + JobSeekerSearch + '%')
											)];	
			/*if(tJobSeekerSearchResults.size() == 1 || Test.isRunningTest())
			{
				PageReference pg = Page.JobSeekerAttributes;
				pg.getParameters().put('id', tJobSeekerSearchResults[0].ID);
				return pg.setRedirect(true);
			}*/
			return null;
		}
		catch(Exception ex)
		{
			return addMessage(ex);
		}
	}
}