src/objects/Business__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Businesses</relationshipLabel>
        <relationshipName>Businesses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Comment__c</fullName>
        <label>Comment</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <label>Location</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Business</label>
    <nameField>
        <label>Business Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Businesses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Communication__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Communications</relationshipLabel>
        <relationshipName>Communications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EC__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>EC</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Communications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Employer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Employer</label>
        <referenceTo>Business__c</referenceTo>
        <relationshipLabel>Communications</relationshipLabel>
        <relationshipName>Communications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Job_Seeker__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Job Seeker</label>
        <referenceTo>Job_Seeker__c</referenceTo>
        <relationshipLabel>Communications</relationshipLabel>
        <relationshipName>Communications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Message__c</fullName>
        <label>Message</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Sent__c</fullName>
        <label>Sent</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Commenced Marketing</fullName>
                </value>
                <value>
                    <fullName>Interview</fullName>
                </value>
                <value>
                    <fullName>Meeting</fullName>
                </value>
                <value>
                    <fullName>Send Resume</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Communication</label>
    <nameField>
        <displayFormat>C{00000}</displayFormat>
        <label>Communication Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Communications</pluralLabel>
    <recordTypes>
        <fullName>Email</fullName>
        <active>true</active>
        <label>Email</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Business__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Business</label>
        <referenceTo>Business__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Employer</fullName>
        <active>true</active>
        <label>Employer</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Employer_Contact__c.object
<CustomObject>
    <fields>
        <fullName>Business__c</fullName>
        <label>Business</label>
        <referenceTo>Business__c</referenceTo>
        <relationshipLabel>Employer Contacts</relationshipLabel>
        <relationshipName>Employer_Contacts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Comment__c</fullName>
        <label>Comment</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Contacted_On__c</fullName>
        <label>Contacted On</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Job_Seeker__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Job Seeker</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Job_Seeker__c.Assigned_To__c</field>
                <operation>equals</operation>
                <valueField>$User.Id</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Job_Seeker__c</referenceTo>
        <relationshipLabel>Employer Contacts</relationshipLabel>
        <relationshipName>Employer_Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Result__c</fullName>
        <label>Result</label>
        <picklist>
            <picklistValues>
                <fullName>Interview</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Resume drop off</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No answer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Call back</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Left message</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No vacancy - Decision maker</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vacancy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Resume sent / apply online</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Do not disturb</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>EC</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Employer_Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Employer Contact</label>
    <nameField>
        <displayFormat>EC{000000000}</displayFormat>
        <label>Employer Contact ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Employer Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Follow_Up__c.object
<CustomObject>
    <fields>
        <fullName>Assigned_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assigned To</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Follow_Ups</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Comment__c</fullName>
        <label>Comment</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Due_Date__c</fullName>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <formula>Employer_Contact__r.Contact_Email__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Email</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Employer_Contact__c</fullName>
        <label>Employer Contact</label>
        <referenceTo>Employer_Contact__c</referenceTo>
        <relationshipLabel>Follow Ups</relationshipLabel>
        <relationshipName>Follow_Ups</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Employer__c</fullName>
        <formula>Employer_Contact__r.Business__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Employer</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Job_Seeker__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Job Seeker</label>
        <referenceTo>Job_Seeker__c</referenceTo>
        <relationshipLabel>Follow Ups</relationshipLabel>
        <relationshipName>Follow_Ups</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Result__c</fullName>
        <label>Result</label>
        <picklist>
            <picklistValues>
                <fullName>Employer undecided</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unsuccessful</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Failed to attend</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Work trial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Negative employer feedback re JSK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Commenced/ETS</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Repeat Call</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Call back</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Resume</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Interview</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Employer Meeting</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Follow Up</label>
    <nameField>
        <displayFormat>FU{0000000000}</displayFormat>
        <label>Follow Up ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Follow Ups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Job_Seeker__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Job Seekers</relationshipLabel>
        <relationshipName>Job_Seekers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Assigned_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assigned To</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Job_Seekers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <label>Job Seeker</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Seekers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/BPCommunicationController.cls
public virtual with sharing class BPCommunicationController 
	extends BPPageBase	
{
    public BPCommunicationController()
    {        
        for(Business__c b : [SELECT ID, 
                                    Name,
                                    Location__c,
                                    Email__c
                            FROM    Business__c
                            WHERE   ID =:getParameter('empId')])
        {
            Employer = b;
            EmailAddress = b.Email__c;
            EmployerAddress = b.Location__c;
        }

        for(Job_Seeker__c jsk : [SELECT ID,
                                        Name,
                                        Account__c 
                                FROM    Job_Seeker__c
                                WHERE ID = :getParameter('jskId')])
        {
            JobSeeker = jsk;
            EmployerContact.Job_Seeker__c = jobSeeker.ID;
        }
        String empAddress = getParameter('ea');
        String contactPerson = getParameter('cp');
        String contactEmail = getParameter('ce');
        String wgSubsidy4 = getParameter('ws4');
        String wgSubsidy13 = getParameter('ws13');
        String wgSubsidy26 = getParameter('ws26');
        String hrs = getParameter('hr');
        String ecMobile = getParameter('ecp');
        if(String.isNotBlank(empAddress))
        {
            EmployerAddress = EncodingUtil.urlDecode(empAddress, 'UTF-8');
        }
        if(String.isNotBlank(contactPerson))
        {
            ContactPerson = contactPerson;
        }
        if(String.isNotBlank(contactEmail))
        {
            EmailAddress = contactEmail;
        }
        if(String.isNotBlank(wgSubsidy4))
        {
            WageSubsidy4Week = wgSubsidy4;
        }
        if(String.isNotBlank(wgSubsidy13))
        {
            WageSubsidy13Week = wgSubsidy13;
        }
        if(String.isNotBlank(wgSubsidy26))
        {
            WageSubsidy26Week = wgSubsidy26;
        }
        if(String.isNotBlank(hrs))
        {
            Hours = hrs;
        }
        if(String.isNotBlank(ecMobile))
        {
            ECMobile = ecMobile;
        }    
    }

    private transient Attachment tBrochure;

    public Business__c Employer
    {
        get
        {
        	if(Employer == null)
            {
                Employer = new Business__c();
            }
            return Employer;
        }
        set;
    }

    public Job_Seeker__c JobSeeker
    {
        get
        {
        	if(JobSeeker == null)
            {
                JobSeeker = new Job_Seeker__c();
            }
            return JobSeeker;
        }
        set;
    }

    public String SearchJobSeekerID
    {
        get;
        set;
    }

    public Blob ResumeBody
    {
        get;
        set;
    }

    public String FileName
    {
        get;
        set;
    }

    public String FileType
    {
        get;
        set;
    }

    public String EmployerAddress
    {
        get;
        set;
    }


    public String EmailAddress
    {
        get;
        set;
    }

    public String Subject
    {
        get;
        set;
    }

    public String Comment
    {
        get;
        set;
    }

    public Employer_Contact__c EmployerContact 
    {
        get
        {
            if(EmployerContact == null)
            {
                EmployerContact = new Employer_Contact__c();
            }
            return EmployerContact;
        }
        set;
    }

    public Attachment Brochure
    {
    	get
    	{
    		if(tBrochure == null)
    		{
    			tBrochure = new Attachment();
    			for(Attachment a : [SELECT ID,
    										Name,
    										Description,
    										ContentType,
    										Body
									FROM 	Attachment
									WHERE 	Description = 'Brochure' AND 
											ParentID = :CurrentUser.AccountId])
				{
					tBrochure = a;
				}				
    		}
    		return tBrochure;
    	}
    	set;
    }

    public Account UserAccount
    {
        get
        {
            if(UserAccount == null)
            {

                UserAccount = BPAccount.getAccount(CurrentUser.AccountId == null ? jobSeeker.Account__c : CurrentUser.AccountId);
            }
            return UserAccount;
        }
        private set;
    }

    public String Today
    {
        get
        {
            return Date.today().format();
        }
    }

    public String ContactPerson
    {
        get;
        set;
    }

    public String WageSubsidy4Week
    {
        get;
        set;
    }

    public String WageSubsidy13Week
    {
        get;
        set;
    }

    public String WageSubsidy26Week
    {
        get;
        set;
    }

    public String Hours
    {
        get;
        set;
    }

    public String ECMobile
    {
        get;
        set;
    }

    public Boolean IncludeResume
    {
    	get;
    	set;
    }

    public Boolean IncludeBrochure
    {
    	get;
    	set;
    }

    public Boolean IncludeSubsidy
    {
    	get
        {
            return false;
        }
    	set;
    }

    public void getJobSeeker()
    {
        String jsId = getParameter('jsId');
        JobSeeker = [SELECT ID,
                            Name,
                            Account__c 
                    FROM    Job_Seeker__c
                    WHERE ID = :getParameter('jsId')];
    }

    public PageReference send()
    {
    	Savepoint sp;
    	try
        {
            throwTestError();
            Boolean valid = true;
            List<Communication__c> communications = new List<Communication__c>();
            List<Messaging.EmailFileAttachment> attachments = new List<Messaging.EmailFileAttachment>();
            Map<String, RecordTypeInfo> commRecordTypesByName = Schema.SObjectType.Communication__c.getRecordTypeInfosByName();
            Blob wgSubsidyPdf;  
            valid = isRequiredFieldValid(EmailAddress, 'Employer email', valid);  
            if(IncludeBrochure == null)
            {
                IncludeBrochure = false;
            } 
            if(IncludeResume)
	        {
	        	valid = isRequiredFieldValid(ResumeBody, 'Resume', valid);
	        	if(valid  || Test.isRunningTest())
	        	{
	        		Messaging.EmailFileAttachment fileAttachment = new Messaging.EmailFileAttachment();
	                fileAttachment.setBody(ResumeBody);
	                fileAttachment.setInline(false);
	                fileAttachment.setFileName(FileName);
	                fileAttachment.setContentType(FileType);
	                attachments.add(fileAttachment);
	        	}
	        }
            /*if(IncludeSubsidy)
            {	            
	            valid = isRequiredFieldValid(EmployerAddress, 'Employer address', valid);	            
	            valid = isRequiredFieldValid(ContactPerson, 'Employer contact person', valid);
	            valid = isRequiredFieldValid(WageSubsidy4Week, '4 week wage subsidy', valid);
	            valid = isRequiredFieldValid(WageSubsidy13Week, '13 week wage subsidy', valid);
	            valid = isRequiredFieldValid(WageSubsidy26Week, '26 week wage subsidy', valid);
	            valid = isRequiredFieldValid(Hours, 'Hours per week', valid);
	            valid = isRequiredFieldValid(ECMobile, 'My Contact Number', valid);

	            if(valid || Test.isRunningTest())
	            {
		            PageReference pg = Page.BPWageSubsidyPDF;
			        setParameters(pg);
			        wgSubsidyPdf = Test.isRunningTest() ? Blob.valueOf('test') : pg.getContentAsPDF();

			        Messaging.EmailFileAttachment fileAttachment = new Messaging.EmailFileAttachment();
	                fileAttachment.setBody(wgSubsidyPdf);
	                fileAttachment.setInline(false);
	                fileAttachment.setFileName('WageSubsidy_' + JobSeeker.Name + '.pdf.');
	                attachments.add(fileAttachment);	                  
	            }	            
	        }	*/        
	        if(!valid && !Test.isRunningTest())
            {
                PageReference pg = Page.BPWageSubsidy;
                setParameters(pg);
                return pg.setRedirect(false);
            }
            if(IncludeBrochure && Brochure.ID != null)
            {
            	Messaging.EmailFileAttachment fileAttachment = new Messaging.EmailFileAttachment();

                fileAttachment.setBody(Brochure.Body);
                fileAttachment.setInline(false);
                fileAttachment.setFileName(Brochure.Name);
                fileAttachment.setContentType(Brochure.ContentType);
                attachments.add(fileAttachment);
            }
            for(Employer_Contact__c ec : [SELECT ID,
	                                            User__c,
	                                            Business__c
	                                    FROM    Employer_Contact__c
	                                    WHERE   ID = :getParameter('ecId')])
	        {
	            EmployerContact = ec;
	        }
            sp = Database.setSavepoint();

            if(EmployerContact.ID == null)
            {
            	EmployerContact.Job_Seeker__c = Jobseeker.ID;
            	EmployerContact.Business__c = Employer.ID;
            	EmployerContact.Result__c =  IncludeResume ? BPConstants.EmployerContact_Result_ResumeSent : BPConstants.EmployerContact_Result_Email;
            	EmployerContact.Contacted_On__c = DateTime.now();
            	insert EmployerContact;
            }
            Employer.Email__c = EmailAddress;
            update Employer;

            String commType = 'Email;';
            if(IncludeResume)
            {
                commType += 'Resume;';
            }
            if(IncludeBrochure)
            {
                commType += 'Brochure;';
            }
            /*if(IncludeSubsidy)
            {
                commType += 'Wage Subsidy;';
            }*/
            Follow_Up__c followup = new Follow_Up__c();
            followup.Employer_Contact__c = EmployerContact.ID;
            followup.Due_Date__c = Date.today().addDays(1);
            followup.Type__c =  commType;
            followup.Assigned_To__c = EmployerContact.User__c;
            followup.Comment__c = Comment;
            insert followup;

            Communication__c comm = new Communication__c();
            comm.Employer__c = Employer.ID;
            comm.Job_Seeker__c = JobSeeker.ID == null ? SearchJobSeekerID : JobSeeker.ID;
            comm.EC__c = UserInfo.getUserId();
            comm.Sent__c = Datetime.now();
            comm.Message__c = Comment;
            comm.Type__c = commType;
            if(wgSubsidyPdf == null)
            {
                comm.RecordTypeId = commRecordTypesByName.get(BPConstants.Communication_RecordType_Email).getRecordTypeId();
                insert comm;
            }
            else
            {
                comm.RecordTypeId = commRecordTypesByName.get(BPConstants.Communication_RecordType_WageSubsidy).getRecordTypeId();
                insert comm;

                Attachment att = new Attachment();
                att.ParentId = comm.ID;
                att.Body = wgSubsidyPdf;
                att.Description = 'Wage subsidy for ' + Employer.Name;
                att.Name = 'Wage subsidy offer for ' + Employer.Name;
                att.ContentType = 'application/pdf';
                insert att;
            }	

            Messaging.SingleEmailMessage msg = new Messaging.SingleEmailMessage();  
            msg.setToAddresses(new List<String>{EmailAddress});
            msg.setTargetObjectId(UserInfo.getUserId());
            msg.setFileAttachments(attachments);
            msg.setSaveAsActivity(false);
            msg.setHtmlBody(Comment);
            msg.setSubject(Subject);
            try
            {
            	Messaging.reserveSingleEmailCapacity(1);
            }
            catch(Exception ex)
			{
				addMessage('Email could not be sent, please try later.');
				msg = new Messaging.SingleEmailMessage(); 
				msg.setSubject('No email capacity');
				msg.setPlainTextBody('No email capacity');
				msg.setSaveAsActivity(false);
				msg.setTargetObjectId(BPUserNoSharing.getAdminUser().ID); 
			}
            Messaging.sendEmail(new List<Messaging.Email>{msg});
            addMessage(ApexPages.Severity.CONFIRM, 'Email has been sent.');
            PageReference pg = Page.BPWageSubsidy;
            pg.getParameters().put('done', '1');
            return pg.setRedirect(true);
        }
        catch(Exception ex)
        {
            return addMessage(ex, sp);
        }
    }

    private void setParameters(PageReference pg)
    {
        pg.getParameters().put('empId', Employer.ID);
        pg.getParameters().put('jskId', JobSeeker.ID);
        pg.getParameters().put('ecId', EmployerContact.ID);
        pg.getParameters().put('ea', EncodingUtil.urlEncode(EmployerAddress, 'UTF-8'));
        pg.getParameters().put('cp', ContactPerson);
        pg.getParameters().put('ce', EmailAddress);
        pg.getParameters().put('ws4', WageSubsidy4Week);
        pg.getParameters().put('ws13', WageSubsidy13Week);
        pg.getParameters().put('ws26', WageSubsidy26Week);     
        pg.getParameters().put('ecp', ECMobile);
        pg.getParameters().put('hr', Hours);
    }
}