src/objects/Business__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Businesses</relationshipLabel>
        <relationshipName>Businesses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Contact_Person__c</fullName>
        <label>Contact Person</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Sensis_ID__c</fullName>
        <externalId>true</externalId>
        <label>Sensis ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Business</label>
    <nameField>
        <label>Business Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Businesses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Business__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Business</label>
        <referenceTo>Business__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Employer_Contact__c.object
<CustomObject>
    <fields>
        <fullName>Business__c</fullName>
        <label>Business</label>
        <referenceTo>Business__c</referenceTo>
        <relationshipLabel>Employer Contacts</relationshipLabel>
        <relationshipName>Employer_Contacts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact_Email__c</fullName>
        <label>Contact Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Contact_Number__c</fullName>
        <label>Contact Number</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Contact_Person__c</fullName>
        <label>Contact Person</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact_Position__c</fullName>
        <label>Contact Position</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contacted_On__c</fullName>
        <label>Contacted On</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Interview_Date__c</fullName>
        <label>Interview/Meeting Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Interview_Time__c</fullName>
        <label>Interview/Meeting Time</label>
        <picklist>
            <picklistValues>
                <fullName>7:00 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7:30 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8:00 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8:30 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9:00 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9:30 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10:00 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10:30 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>11:00 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>11:30 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12:00 PM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12:30 PM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1:00 PM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1:30 PM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2:00 PM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2:30 PM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3:00 PM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3:30 PM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4:00 PM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4:30 PM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5:00 PM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5:30 PM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6:00 PM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6:30 PM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7:00 PM</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Job_Seeker__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Job Seeker</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Job_Seeker__c.Assigned_To__c</field>
                <operation>equals</operation>
                <valueField>$User.Id</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Job_Seeker__c</referenceTo>
        <relationshipLabel>Employer Contacts</relationshipLabel>
        <relationshipName>Employer_Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Result__c</fullName>
        <label>Result</label>
        <picklist>
            <picklistValues>
                <fullName>Interview</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Resume drop off</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No answer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Call back</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Left message</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No vacancy - Decision maker</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vacancy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Resume sent / apply online</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Do not disturb</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Sensis_ID__c</fullName>
        <externalId>true</externalId>
        <label>Sensis ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>EC</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Employer_Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Employer Contact</label>
    <nameField>
        <displayFormat>EC{000000000}</displayFormat>
        <label>Employer Contact ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Employer Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Follow_Up__c.object
<CustomObject>
    <fields>
        <fullName>Actioned__c</fullName>
        <label>Actioned</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Assigned_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assigned To</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Follow_Ups</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact_Number__c</fullName>
        <formula>Employer_Contact__r.Contact_Number__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Contact Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Due_Date__c</fullName>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <formula>Employer_Contact__r.Contact_Email__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Email</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Employer_Contact_Person__c</fullName>
        <formula>Employer_Contact__r.Contact_Person__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Employer Contact  Person</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Employer_Contact_Position__c</fullName>
        <formula>Employer_Contact__r.Contact_Position__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Employer Contact Position</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Employer_Contact__c</fullName>
        <label>Employer Contact</label>
        <referenceTo>Employer_Contact__c</referenceTo>
        <relationshipLabel>Follow Ups</relationshipLabel>
        <relationshipName>Follow_Ups</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Employer__c</fullName>
        <formula>Employer_Contact__r.Business__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Employer</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Interview_Date__c</fullName>
        <formula>Employer_Contact__r.Interview_Date__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Interview Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Interview_Time__c</fullName>
        <formula>TEXT(Employer_Contact__r.Interview_Time__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Interview Time</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Job_Seeker__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Job Seeker</label>
        <referenceTo>Job_Seeker__c</referenceTo>
        <relationshipLabel>Follow Ups</relationshipLabel>
        <relationshipName>Follow_Ups</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Result__c</fullName>
        <label>Result</label>
        <picklist>
            <picklistValues>
                <fullName>Employer undecided</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unsuccessful</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Failed to attend</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Work trial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Negative employer feedback re JSK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Commenced/ETS</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Repeat Call</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Call back</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Resume</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Interview</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Employer Meeting</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Follow Up</label>
    <nameField>
        <displayFormat>FU{0000000000}</displayFormat>
        <label>Follow Up ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Follow Ups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Job_Seeker__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Job Seekers</relationshipLabel>
        <relationshipName>Job_Seekers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Assigned_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assigned To</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Job_Seekers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Marketing_Ended__c</fullName>
        <label>Marketing Ended</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Suburb__c</fullName>
        <label>Suburb</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>X1_Marketable_Attribute__c</fullName>
        <label>1  Marketable Attribute</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>X2_Marketable_Attribute__c</fullName>
        <label>2 Marketable Attribute</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>X3_Marketable_Attribute__c</fullName>
        <label>3 Marketable Attribute</label>
        <type>TextArea</type>
    </fields>
    <label>Job Seeker</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Seekers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/JobSeekerExtension.cls
public with sharing class JobSeekerExtension 
    extends BPPageBase
{
    public JobSeekerExtension(ApexPages.StandardController ctrlr) 
    {
        if(!Test.isRunningTest())
        {
            ctrlr.addFields(new String[]{'Account__c','X1_Marketable_Attribute__c','X2_Marketable_Attribute__c','X3_Marketable_Attribute__c'});
        }    	
        controller = ctrlr;
    }

    private ApexPages.StandardController controller;

    public List<Employer_Contact__c> EmployerContacts 
    {
    	get 
    	{
    		if(EmployerContacts == null)
    		{
    			EmployerContacts = [SELECT Id, 
    										Name, 
    										Contacted_On__c, 
    										Result__c, 
    										User__c, 
    										Contact_Number__c, 
    										Contact_Email__c, 
    										Interview_Time__c, 
                                            Interview_Date__c,
    										Sensis_ID__c, 
    										Contact_Person__c, 
    										Contact_Position__c, 
                                            Category__c,
    										Business__c,
                                            Business__r.Name
									FROM 	Employer_Contact__c
									WHERE 	Job_Seeker__c = :controller.getId()  
									ORDER BY Contacted_On__c DESC NULLS LAST];
    		}
    		return EmployerContacts;
    	}
    	private set;
    }

    public List<Follow_Up__c> FollowUps 
    {
        get 
        {
            if(FollowUps == null)
            {
                FollowUps = [SELECT Id, 
                                    Name,
                                    Employer_Contact__c, 
                                    Due_Date__c, 
                                    Type__c, 
                                    Actioned__c, 
                                    Assigned_To__c, 
                                    Contact_Number__c, 
                                    Email__c, 
                                    Interview_Time__c, 
                                    Interview_Date__c,
                                    Employer__c,
                                    Employer_Contact_Person__c, 
                                    Employer_Contact_Position__c, 
                                    Interview_Result__c, 
                                    Meeting_Result__c 
                            FROM    Follow_Up__c
                            WHERE   Job_Seeker__c = :controller.getId()   
                            ORDER BY Due_Date__c DESC];
            }
            return FollowUps;
        }
        private set;
    }

    public PageReference checkAttributes()
    {
        try
        {
            throwTestError();
            Job_Seeker__c jSeeker = (Job_Seeker__c)controller.getRecord();
            if(getParameter('redirect') == 'no')
            {
                return null;
            }
            if(String.isEmpty(jSeeker.X1_Marketable_Attribute__c) ||
                    String.isEmpty(jSeeker.X2_Marketable_Attribute__c) ||
                    String.isEmpty(jSeeker.X3_Marketable_Attribute__c))
            {
                return null;
            }
            PageReference pg = Page.EmployerSearch;
            pg.getParameters().put('id', jSeeker.ID);
            return pg.setRedirect(true);
        }
        catch(Exception ex)
        {
            return addMessage(ex);
        }
    }

    public PageReference saveAndCommenceMarketing()
    {
        try
        {
            throwTestError();
            if(saveOverride() == null)
            {
                return null;
            }
            return commenceMarketing();
        }
        catch(Exception ex)
        {
            return addMessage(ex);
        }
    }


    public PageReference commenceMarketing()
    {
        try
        {
            throwTestError();
            Job_Seeker__c jSeeker = (Job_Seeker__c)controller.getRecord();
            if(String.isEmpty(jSeeker.X1_Marketable_Attribute__c) ||
                    String.isEmpty(jSeeker.X2_Marketable_Attribute__c) ||
                    String.isEmpty(jSeeker.X3_Marketable_Attribute__c))
            {
                return addMessage('3 Most Marketable Attributes are required before commencing marketing.');
            }
            update jSeeker;
            PageReference pg = Page.EmployerSearch;
            pg.getParameters().put('id', jSeeker.ID);
            return pg.setRedirect(true);
        }
        catch(Exception ex)
        {
            return addMessage(ex);
        }
    }

    public PageReference saveOverride()
    {
        try
        {
            throwTestError();   
            Job_Seeker__c jSeeker = (Job_Seeker__c)controller.getRecord();     
            if(String.isBlank(jSeeker.Account__c) && CurrentUser.ContactID != null)
            {
                jSeeker.Account__c = CurrentUser.Contact.AccountID;

            }             
            if(jSeeker.Assigned_To__c == null && jSeeker.Marketing_Ended__c == null)
            {
                jSeeker.Assigned_To__c = CurrentUser.ID;
            }  

            Boolean valid = true; 
            valid = isRequiredFieldValid(jSeeker.Suburb__c, 'Suburb', valid);
            valid = isRequiredFieldValid(jSeeker.State__c, 'State', valid);
            if(!valid)
            {
                return null;
            }
            return controller.save();
        }
        catch(Exception ex)
        {
            return addMessage(ex);
        }
    }
}