src/objects/Business__c.object
<CustomObject>
    <fields>
        <fullName>Contact_Person__c</fullName>
        <label>Contact Person</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Business</label>
    <nameField>
        <label>Business Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Businesses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Employer_Contact__c.object
<CustomObject>
    <fields>
        <fullName>Business__c</fullName>
        <label>Business</label>
        <referenceTo>Business__c</referenceTo>
        <relationshipLabel>Employer Contacts</relationshipLabel>
        <relationshipName>Employer_Contacts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Contact_Email__c</fullName>
        <label>Contact Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Contact_Person__c</fullName>
        <label>Contact Person</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Job_Seeker__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Job Seeker</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Job_Seeker__c.Assigned_To__c</field>
                <operation>equals</operation>
                <valueField>$User.Id</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Job_Seeker__c</referenceTo>
        <relationshipLabel>Employer Contacts</relationshipLabel>
        <relationshipName>Employer_Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Employer Contact</label>
    <nameField>
        <displayFormat>EC{000000000}</displayFormat>
        <label>Employer Contact ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Employer Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Job_Seeker__c.object
<CustomObject>
    <label>Job Seeker</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Seekers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TestBPCommunicationsController.cls
@isTest
private class TestBPCommunicationsController 
{
	private static testMethod void test1()
	{
		Job_Seeker__c js = TestJobSeekerExtension.insertJobSeeker();
		Employer_Contact__c ec = TestJobSeekerExtension.insertEmployerContact(js);

		Test.setCurrentPage(Page.BPWageSubsidy);
		ApexPages.currentPage().getParameters().put('empId', ec.Business__c);
		ApexPages.currentPage().getParameters().put('jskId', js.ID);
		ApexPages.currentPage().getParameters().put('ea', 'test');
        ApexPages.currentPage().getParameters().put('cp', 'test');
        ApexPages.currentPage().getParameters().put('ce', 'test@test.com');
        ApexPages.currentPage().getParameters().put('ws4', 'test');
        ApexPages.currentPage().getParameters().put('ws13', 'test');
        ApexPages.currentPage().getParameters().put('ws26', 'test');
        ApexPages.currentPage().getParameters().put('hr', 'test');
        ApexPages.currentPage().getParameters().put('ecp', 'test');
		BPCommunicationController ext = new BPCommunicationController();

		system.assert(ext.Employer != null);
		system.assert(ext.JobSeeker != null);
		system.assert(ext.EmployerContact != null);
		system.assert(ext.UserAccount != null);
		system.assert(ext.Today != null);
		system.assert(ext.WageSubsidy13Week != null);
		system.assert(ext.WageSubsidy26Week != null);
		system.assert(ext.Hours != null);
		system.debug(ext.Brochure);
		ext.ECMobile = 'test';
		system.assert(ext.ECMobile != null);
		ext.IncludeResume = true;
		ext.ResumeBody = Blob.valueOf('test');
		ext.FileName = 'test';
		ext.FileType = 'test';
		ext.send();

		ext.send();

		ext.EmployerContact.Contact_Person__c = null;
		ext.EmployerContact.Contact_Email__c = null;

		ext.send();
	}

	private static testMethod void testError()
	{
		BPCommunicationController ext = new BPCommunicationController();
		ext.testErrorEnabled = true;

		try
		{
			ext.send();
		}
		catch (Exception ex)
		{}
	}

}