src/objects/Business__c.object
<CustomObject>
    <fields>
        <fullName>Address__c</fullName>
        <label>Address</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Business</label>
    <nameField>
        <label>Business Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Businesses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Communication__c.object
<CustomObject>
    <fields>
        <fullName>Gateway_Reference__c</fullName>
        <externalId>true</externalId>
        <label>Gateway Reference</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Job_Seeker__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Job Seeker</label>
        <referenceTo>Job_Seeker__c</referenceTo>
        <relationshipLabel>Communications</relationshipLabel>
        <relationshipName>Communications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Message__c</fullName>
        <label>Message</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Number__c</fullName>
        <label>Number</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Sent__c</fullName>
        <label>Sent</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Commenced Marketing</fullName>
                </value>
                <value>
                    <fullName>Interview</fullName>
                </value>
                <value>
                    <fullName>Meeting</fullName>
                </value>
                <value>
                    <fullName>Send Resume</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Communication</label>
    <nameField>
        <displayFormat>C{00000}</displayFormat>
        <label>Communication Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Communications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Employer_Contact__c.object
<CustomObject>
    <fields>
        <fullName>Address__c</fullName>
        <label>Address</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Business__c</fullName>
        <label>Business</label>
        <referenceTo>Business__c</referenceTo>
        <relationshipLabel>Employer Contacts</relationshipLabel>
        <relationshipName>Employer_Contacts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Interview_Date__c</fullName>
        <label>Interview/Meeting Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Interview_Time__c</fullName>
        <label>Interview/Meeting Time</label>
        <picklist>
            <picklistValues>
                <fullName>7:00 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7:30 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8:00 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8:30 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9:00 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9:30 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10:00 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10:30 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>11:00 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>11:30 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12:00 PM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12:30 PM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1:00 PM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1:30 PM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2:00 PM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2:30 PM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3:00 PM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3:30 PM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4:00 PM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4:30 PM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5:00 PM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5:30 PM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6:00 PM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6:30 PM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7:00 PM</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Job_Seeker__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Job Seeker</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Job_Seeker__c.Assigned_To__c</field>
                <operation>equals</operation>
                <valueField>$User.Id</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Job_Seeker__c</referenceTo>
        <relationshipLabel>Employer Contacts</relationshipLabel>
        <relationshipName>Employer_Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Result__c</fullName>
        <label>Result</label>
        <picklist>
            <picklistValues>
                <fullName>Interview</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Resume drop off</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No answer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Call back</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Left message</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No vacancy - Decision maker</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vacancy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Resume sent / apply online</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Do not disturb</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Employer Contact</label>
    <nameField>
        <displayFormat>EC{000000000}</displayFormat>
        <label>Employer Contact ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Employer Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Job_Seeker__c.object
<CustomObject>
    <label>Job Seeker</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Seekers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/SMS_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <fields>
        <fullName>From__c</fullName>
        <label>From</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Minimum_Balance__c</fullName>
        <label>Minimum Balance</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Password__c</fullName>
        <label>Password</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>URL__c</fullName>
        <label>URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Username__c</fullName>
        <label>Username</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>SMS Settings</label>
</CustomObject>

src/classes/BPSMSUtilities.cls
public with sharing class BPSMSUtilities 
{
    private static String BaseURL
    {
        get
        {
            return SMS_Settings__c.getInstance().URL__c + 
                    'username=' + 
                    SMS_Settings__c.getInstance().Username__c + 
                    '&password=' + 
                    SMS_Settings__c.getInstance().Password__c;
        }
    }
    
    public static String sendSMS(String message, String phNumber, Integer reference)
    {
    	return sendSMS(message, phNumber, reference, true);
    }

    public static void sendMeetingSMS(Employer_Contact__c employerContact, String mobileNumber, String siteName)
    {
        String type;
        if(employerContact.Result__c == BPConstants.EmployerContact_Result_Interview)
        {
            type = 'an ' + BPConstants.EmployerContact_Result_Interview;
        }
        else
        {
            type = 'an employer meeting';
        }
        String message = siteName + ' has arranged for you to have ' + type + ' with ' + 
                    employerContact.Business__r.Name + ' ' +
                    employerContact.Address__c +
                    ' on ' + employerContact.Interview_Date__c.format() + 
                    ' at ' + employerContact.Interview_Time__c + 
                    '. Please notify us if you are unable to attend.';
        String phNumber = BPSMSUtilities.cleanPhoneNumber(mobileNumber);
        String smsReference = sendSMS(message, phNumber, null); 
        Communication__c notification = new Communication__c(Job_Seeker__c = employerContact.Job_Seeker__c,
                                                Number__c = phNumber,
                                                Message__c = message,
                                                Type__c = type);
        notification.RecordTypeId = (new BPPageBase()).CommunicationRecordTypesByName.get(BPConstants.Communication_RecordType_SMSNotification).getRecordTypeID();
        if(smsReference != null)
        {
            notification.Sent__c = Datetime.now();
            notification.Gateway_Reference__c = smsReference;
            
        }
        insert notification;
    }

    private static String sendSMS(String message, String phNumber, Integer reference, Boolean checkBalance)
    {
        if(String.isBlank(phNumber))
        {
            throw new BPException('Mobile phone number is required to send an SMS.');
        }
        phNumber = cleanPhoneNumber(phNumber);     
        if(checkBalance)
        {
            Integer balance = getBalance(Test.isRunningTest());
            if(balance < SMS_Settings__c.getInstance().Minimum_Balance__c)
            {
                if(balance == 0)
                {
                    return null;
                }
                if(balance < 10)
                {
                    sendSMS('Credit low (' + balance.format() + ')', '0404240508', 9999999, false);
                }
            }
        }

        message = EncodingUtil.urlEncode(message, 'UTF-8');
        HttpRequest request = new HttpRequest();
        request.setMethod('POST');
        String url = BaseURL + 
                        '&to=' + phNumber + 
                        '&from=' + SMS_Settings__c.getInstance().From__c + 
                        '&message=' + message + 
                        (reference == null ? '' : ('&ref=' + reference.format().replace(',', ''))) + 
                        '&maxsplit=5';
        request.setEndPoint(url);
        String[] response;
        if(Test.isRunningTest())
        {
           response = new String[]{'test', 'test', 'test'};
        }
        else
        {
            Http http = new Http();
            HTTPResponse res = http.send(request);
            response = res.getBody().split(':');
        }
       
        if(response.size() > 0)
        {
            if(response[0] == 'BAD')
	        {
	            throw new BPException('SMS gateway rejected the message due to an invalid number.');
	        }
            else if(response[0] == 'ERROR')
            {
                throw new BPException(response[1]);
            }
            return response[2];
        }
        return null;
    }

    public static String cleanPhoneNumber(String phNumber)
    {
        phNumber = phNumber.replace('(', '').replace(')', '').deleteWhitespace();
        Pattern mobilePattern = Pattern.compile('04[0-9]{8}');
        if(!(mobilePattern.matcher(phNumber).matches()))
        {
            throw new BPException('Mobile phone number must be in the format 0499999999.');
        }
        return phNumber;
    }

    @TestVisible
    private static Integer getBalance(Boolean isTest)
    {
        Integer minBalance = Test.isRunningTest() ? 20 : SMS_Settings__c.getInstance().Minimum_Balance__c.intValue();
    	try
    	{
	        HttpRequest request = new HttpRequest();
	        request.setMethod('POST');
	        request.setEndPoint(BaseUrl + '&action=balance');
	        Http http = new Http();
	         String[] response;
            if(Test.isRunningTest())
            {
               response = new String[]{'test', '1'};
            }
            else
            {
    	        HTTPResponse res = http.send(request);	        
    	        response = res.getBody().split(':');
            }
	        if(response.size() != 2 || response[0] == 'ERROR')
	        {
	            return minBalance;
	        }   
        	return Integer.valueOf(response[1]); 
    	}
    	catch(Exception ex)
    	{
    		return minBalance;
    	}
    }
}