src/objects/Business__c.object
<CustomObject>
    <label>Business</label>
    <nameField>
        <label>Business Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Businesses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Employer_Contact__c.object
<CustomObject>
    <fields>
        <fullName>Business__c</fullName>
        <label>Business</label>
        <referenceTo>Business__c</referenceTo>
        <relationshipLabel>Employer Contacts</relationshipLabel>
        <relationshipName>Employer_Contacts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Job_Seeker__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Job Seeker</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Job_Seeker__c.Assigned_To__c</field>
                <operation>equals</operation>
                <valueField>$User.Id</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Job_Seeker__c</referenceTo>
        <relationshipLabel>Employer Contacts</relationshipLabel>
        <relationshipName>Employer_Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Employer Contact</label>
    <nameField>
        <displayFormat>EC{000000000}</displayFormat>
        <label>Employer Contact ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Employer Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Follow_Up__c.object
<CustomObject>
    <fields>
        <fullName>Due_Date__c</fullName>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Employer_Contact__c</fullName>
        <label>Employer Contact</label>
        <referenceTo>Employer_Contact__c</referenceTo>
        <relationshipLabel>Follow Ups</relationshipLabel>
        <relationshipName>Follow_Ups</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Job_Seeker__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Job Seeker</label>
        <referenceTo>Job_Seeker__c</referenceTo>
        <relationshipLabel>Follow Ups</relationshipLabel>
        <relationshipName>Follow_Ups</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Repeat Call</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Call back</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Resume</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Interview</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Employer Meeting</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Follow Up</label>
    <nameField>
        <displayFormat>FU{0000000000}</displayFormat>
        <label>Follow Up ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Follow Ups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Job_Seeker__c.object
<CustomObject>
    <label>Job Seeker</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Seekers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/BPCreateFollowupController.cls
public with sharing class BPCreateFollowupController 
	extends BPPageBase
{
    public BPCreateFollowupController() {
}

     public Follow_Up__c NewEmployerFollowup
    {
        get 
        {
            if(NewEmployerFollowup == null)
            {
                NewEmployerFollowup = new Follow_Up__c(Type__c = BPConstants.FollowUp_Type_CallEmployer);
            }
            return NewEmployerFollowup;
        }
        set;
    }

    public Follow_Up__c NewJobseekerFollowup
    {
        get 
        {
            if(NewJobseekerFollowup == null)
            {
                NewJobseekerFollowup = new Follow_Up__c(Type__c = BPConstants.FollowUp_Type_CallJobseeker);
            }
            return NewJobseekerFollowup;
        }
        set;
    }

    public void createFollowup()
    {
        try
        {
            /*PageReference pg = Page.FollowUp;
            //followUp = new Follow_Up__c(Employer_Contact__c = followup.Employer_Contact__c, Job_Seeker__c = followup.Job_Seeker__c);
            pg.getParameters().put('jskId', followup.Job_Seeker__c);
            pg.getParameters().put('ecId', followup.Employer_Contact__c);
            pg.getParameters().put('empId', followup.Employer_Contact__r.Business__c);
            return pg.setRedirect(true);*/
 system.debug(getParameter('necID') );     
            for(Employer_Contact__c ec : [SELECT ID, 
                                                Job_Seeker__c 
                                        FROM    Employer_Contact__c 
                                        WHERE   ID = :getParameter('necID')])
            {
                Integer i = 0;
                if(NewEmployerFollowup.Due_Date__c != null)
                {
                    NewEmployerFollowup.Employer_Contact__c = ec.ID;
                    NewEmployerFollowup.Job_Seeker__c =  ec.Job_Seeker__c;
                    upsert NewEmployerFollowup;
                    i++;
                }
                if(NewJobseekerFollowup.Due_Date__c != null)
                {
                    NewJobseekerFollowup.Employer_Contact__c = ec.ID;
                    NewJobseekerFollowup.Job_Seeker__c = ec.Job_Seeker__c;
                    upsert NewJobseekerFollowup;
                    i++;
                }
                if(i > 0)
                {
                    addMessage(ApexPages.Severity.INFO, String.valueOf(i) + ' new followup(s) created.');
                }
                else
                {
                    addMessage('Followup date is required');
                }
            }
        }
        catch(Exception ex)
        {
            addMessage(ex);
        }
    }

}