src/objects/Employer_Contact__c.object
<CustomObject>
    <fields>
        <fullName>Interview_Date__c</fullName>
        <label>Interview/Meeting Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Interview_Time__c</fullName>
        <label>Interview/Meeting Time</label>
        <picklist>
            <picklistValues>
                <fullName>7:00 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7:30 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8:00 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8:30 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9:00 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9:30 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10:00 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10:30 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>11:00 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>11:30 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12:00 PM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12:30 PM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1:00 PM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1:30 PM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2:00 PM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2:30 PM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3:00 PM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3:30 PM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4:00 PM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4:30 PM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5:00 PM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5:30 PM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6:00 PM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6:30 PM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7:00 PM</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Job_Seeker__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Job Seeker</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Job_Seeker__c.Assigned_To__c</field>
                <operation>equals</operation>
                <valueField>$User.Id</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Job_Seeker__c</referenceTo>
        <relationshipLabel>Employer Contacts</relationshipLabel>
        <relationshipName>Employer_Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Result__c</fullName>
        <label>Result</label>
        <picklist>
            <picklistValues>
                <fullName>Interview</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Resume drop off</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No answer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Call back</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Left message</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No vacancy - Decision maker</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vacancy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Resume sent / apply online</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Do not disturb</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Employer Contact</label>
    <nameField>
        <displayFormat>EC{000000000}</displayFormat>
        <label>Employer Contact ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Employer Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Follow_Up__c.object
<CustomObject>
    <fields>
        <fullName>Action_Taken__c</fullName>
        <label>Action Taken</label>
        <picklist>
            <picklistValues>
                <fullName>Interview</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Resume drop off</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No answer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Left message</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No vacancy - Decision maker</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vacancy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Resume sent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sent another jobseeker</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wage subsidy details sent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Work trial organised</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Do not disturb</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Call back</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wage subsidy signed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Assigned_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assigned To</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Follow_Ups</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Due_Date__c</fullName>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Employer_Contact__c</fullName>
        <label>Employer Contact</label>
        <referenceTo>Employer_Contact__c</referenceTo>
        <relationshipLabel>Follow Ups</relationshipLabel>
        <relationshipName>Follow_Ups</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Interview_Date__c</fullName>
        <formula>Employer_Contact__r.Interview_Date__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Interview Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Interview_Time__c</fullName>
        <formula>TEXT(Employer_Contact__r.Interview_Time__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Interview Time</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Job_Seeker__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Job Seeker</label>
        <referenceTo>Job_Seeker__c</referenceTo>
        <relationshipLabel>Follow Ups</relationshipLabel>
        <relationshipName>Follow_Ups</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Result__c</fullName>
        <label>Result</label>
        <picklist>
            <picklistValues>
                <fullName>Employer undecided</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unsuccessful</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Failed to attend</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Work trial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Negative employer feedback re JSK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Commenced/ETS</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Follow Up</label>
    <nameField>
        <displayFormat>FU{0000000000}</displayFormat>
        <label>Follow Up ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Follow Ups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Job_Seeker__c.object
<CustomObject>
    <fields>
        <fullName>Assigned_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assigned To</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Job_Seekers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Placed_Date__c</fullName>
        <label>Placed Date</label>
        <type>Date</type>
    </fields>
    <label>Job Seeker</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Seekers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Live_Session__c.object
<CustomObject>
    <fields>
        <fullName>Job_Seeker__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Job Seeker</label>
        <referenceTo>Job_Seeker__c</referenceTo>
        <relationshipLabel>Live Sessions</relationshipLabel>
        <relationshipName>Live_Sessions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Live Session</label>
    <nameField>
        <displayFormat>LS{000000}</displayFormat>
        <label>Live Session Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Live Sessions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestBPReports.cls
@isTest
private class TestBPReports 
{
	@IsTest(SeeAllData=true)
	private static void  test1()
	{
		User u = [SELECT ID,
						AccountID
				FROM	User 
				WHERE	Profile.Name = 'BPlus Community' AND 
						AccountID != null AND
						IsActive = true
				LIMIT 1];

		Job_Seeker__c js = TestJobSeekerExtension.insertJobSeeker();
		Follow_Up__c fu = new Follow_Up__c();
		fu.Due_Date__c = Date.today();
		fu.Job_Seeker__c = js.ID;
		fu.Employer_Contact__c = TestJobSeekerExtension.insertEmployerContact(js).ID;
		fu.Action_Taken__c = BPConstants.EmployerContact_Result_LeftMessage;
		fu.Assigned_To__c = u.ID;
		insert fu;

		fu = new Follow_Up__c();
		fu.Due_Date__c = Date.today();
		fu.Job_Seeker__c = js.ID;
		fu.Employer_Contact__c = TestJobSeekerExtension.insertEmployerContact(js).ID;
		fu.Action_Taken__c = BPConstants.EmployerContact_Result_Interview;
		fu.Assigned_To__c = u.ID;
		insert fu;

		fu = new Follow_Up__c();
		fu.Due_Date__c = Date.today();
		fu.Job_Seeker__c = js.ID;
		fu.Employer_Contact__c = TestJobSeekerExtension.insertEmployerContact(js).ID;
		fu.Action_Taken__c = BPConstants.FollowUp_Type_Placed;
		fu.Assigned_To__c = u.ID;
		insert fu;

		js.Placed_Date__c = Date.today();
		update js;

		Employer_Contact__c ec = new Employer_Contact__c(ID = fu.Employer_Contact__c);
		ec.Result__c = BPConstants.EmployerContact_Result_Interview;
		ec.Interview_Date__c = Date.today();
		ec.Interview_Time__c = 'test';
		update ec;

		ec = new Employer_Contact__c(ID = fu.Employer_Contact__c);
		ec.Result__c = BPConstants.EmployerContact_Result_Vacancy;
		update ec;

		BPReports ext = new BPReports();
		Test.setCurrentPage(Page.BPReports);
		ApexPages.currentPage().getParameters().put('jskId', js.ID);
		system.assert(ext.JobSeeker != null);

		System.runAs(u)
		{
			ApexPages.currentPage().getParameters().put('acc', u.AccountID);
			system.assert(ext.ECPerfomance != null);

			system.assert(ext.Periods != null);
			system.assert(ext.JobSeekers != null);
			system.assert(ext.ECs != null);	
			system.assert(ext.ECVacancies != null);		
			system.assert(ext.SiteECs != null);
			system.assert(ext.Total.Calls != null);
			system.assert(ext.Total.Meetings != null);
			system.assert(ext.Total.Vacancies != null);
			system.assert(ext.Total.Resumes != null);
			system.assert(ext.Total.Placements != null);

			
			
		}

		Live_Session__c ls = new Live_Session__c();
		ls.Job_Seeker__c = js.ID;
		insert ls;

		//ApexPages.currentPage().getParameters().put('jskId', js.ID);
		

		ext.JobSeeker = null;
		ApexPages.currentPage().getParameters().put('sessId', ls.ID);
		ApexPages.currentPage().getParameters().put('chkId', js.ID);
		system.assert(ext.JobSeeker != null);
		system.assert(ext.BrokeredLiveJobSeeker != null);


		system.assert(ext.ECPerfomance != null);
		for(BPReports.ECWrapper w : ext.ECPerfomance)
		{
			system.assert(w.Placements != null);
			system.assert(w.Meetings != null);
			system.assert(w.Followups != null);
			system.assert(w.FollowupsCompleted != null);
			system.assert(w.FollowupRatio != null);
			system.assert(w.Calls != null);
			system.assert(w.MeetingRatio != null);
			system.assert(w.PlacementRatio != null);
			system.assert(w.NoFurtherAction != null);
			system.assert(w.ResumesSent != null);
			system.assert(w.Disconnected != null);
			system.assert(w.NoVacancy != null);
			system.assert(w.Vacancies != null);
			system.assert(w.MeetingPlacementRatio != null);
			system.assert(w.NoAnswerRatio != null);
			system.assert(w.NoFurtherActionRatio != null);
			system.assert(w.ResumeToMeetingRatio != null);
			w.incrementPacements(1.0);
		} 

		ext.SelectedPeriod = null;
		ext.setDates();

		ext.SelectedPeriod = '1';
		ext.setDates();

		ext.SelectedPeriod = '2';
		ext.setDates();

		ext.SelectedPeriod = '3';
		ext.setDates();

		ApexPages.currentPage().getParameters().put('rp', 'test');
		ext.openReport();

		ApexPages.currentPage().getParameters().put('jskId', js.ID);
		system.assert(ext.JobSeeker != null);

		system.assert(ext.parseDate(null, null) == null);
		system.assert(ext.parseDate(Date.today().format(), Date.today()) == Date.today());
		system.assert(ext.parseDate('bad date', Date.today()) == null);

		BPReports.sendECReport(u.AccountID, Date.today(),  Date.today());
	}

	private static testMethod void  testErrors()
	{
		Test.setCurrentPage(Page.BPReports);
		BPReports ext = new BPReports();
		ext.testErrorEnabled = true;

		try
		{
			ext.openReport();
		}
		catch(Exception ex)
		{}
		try
		{
			ext.setDates();
		}
		catch(Exception ex)
		{}
	}	
}