src/objects/Job_Seeker__c.object
<CustomObject>
    <fields>
        <fullName>Assigned_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assigned To</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Job_Seekers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Marketing_Only__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Marketing Only</label>
        <type>Checkbox</type>
    </fields>
    <label>Job Seeker</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Seekers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Marketing_Only__c</fullName>
        <formula>IF(ISBLANK(ContactId), false, Contact.Account.Marketing_Only__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Marketing Only</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/BPNavBarController.cls
public with sharing class BPNavBarController
	extends BPPageBase
{
	public Job_Seeker__c MarketingOnlyJobSeeker 
	{
		get
		{
			if(MarketingOnlyJobSeeker == null)
			{
				MarketingOnlyJobSeeker = new Job_Seeker__c();
				for(Job_Seeker__c js : [SELECT	ID
										FROM	Job_Seeker__c 
										WHERE	Assigned_To__c = :UserInfo.getUserId() AND 
												Assigned_To__r.Marketing_Only__c = true]) 
				{
					MarketingOnlyJobSeeker = js;
				}
			}
			return MarketingOnlyJobSeeker;
		}
		set;
	}
}