src/objects/Job_Seeker__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Job Seekers</relationshipLabel>
        <relationshipName>Job_Seekers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>ACT</fullName>
                </value>
                <value>
                    <fullName>NSW</fullName>
                </value>
                <value>
                    <fullName>NT</fullName>
                </value>
                <value>
                    <fullName>QLD</fullName>
                </value>
                <value>
                    <fullName>SA</fullName>
                </value>
                <value>
                    <fullName>TAS</fullName>
                </value>
                <value>
                    <fullName>VIC</fullName>
                </value>
                <value>
                    <fullName>WA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Suburb__c</fullName>
        <label>Suburb</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>X1_Marketable_Attribute__c</fullName>
        <label>1  Marketable Attribute</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>X2_Marketable_Attribute__c</fullName>
        <label>2 Marketable Attribute</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>X3_Marketable_Attribute__c</fullName>
        <label>3 Marketable Attribute</label>
        <type>TextArea</type>
    </fields>
    <label>Job Seeker</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Seekers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TestJobSeekerExtension.cls
@isTest
public class TestJobSeekerExtension 
{
	private static testMethod void test1()
	{
		Job_Seeker__c js = insertJobSeeker();

		JobSeekerExtension ext = new JobSeekerExtension(new ApexPages.StandardController(js));

		system.assert(ext.EmployerContacts != null);
		system.assert(ext.FollowUps != null);

		system.assert(ext.checkAttributes() == null);
		system.assert(ext.commenceMarketing() == null);

		js.X1_Marketable_Attribute__c = 'test';
        js.X2_Marketable_Attribute__c = 'test';
        js.X3_Marketable_Attribute__c = 'test';
        update js;

		system.assert(ext.checkAttributes() != null);
		system.assert(ext.commenceMarketing() != null);

		ext.testErrorEnabled = true;
		try
		{
			ext.checkAttributes();
		}
		catch(Exception ex)
		{}
		try
		{
			ext.commenceMarketing();
		}
		catch(Exception ex)
		{}
	}

	public static Job_Seeker__c insertJobSeeker()
	{
		Account a = new Account(Name = 'test');
		insert a;

		Job_Seeker__c js = new Job_Seeker__c();
		js.Account__c = a.ID;
		js.Name = 'test';
		js.JSK_ID__c = 'test';
		js.Suburb__c = 'Aldgate';
		js.State__c = 'SA';
		insert js;
		return js;
	}
}