src/objects/SMS_Notification__c.object
<CustomObject>
    <fields>
        <fullName>Delivered__c</fullName>
        <label>Delivered</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Delivery_Status__c</fullName>
        <label>Delivery Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Gateway_Reference__c</fullName>
        <externalId>true</externalId>
        <label>Gateway Reference</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>SMS Notification</label>
    <nameField>
        <displayFormat>SMS{00000}</displayFormat>
        <label>SMS Notifications Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SMS Notifications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/BPWebservices.cls
@RestResource(urlMapping='/updateSMSDelivery/*')
global class BPWebservices 
{   
    // call using URL https://brokeredplus.force.com/bplus/services/apexrest/updateSMSDelivery/confirm?ref=<refNumber>
    @HttpGet
    global static void confirm()
    {
        String smsref = RestContext.request.params.get('smsref');
        String status = RestContext.request.params.get('status');

        updateSMSNotification(smsref, status);
    }

    @TestVisible
    private static void updateSMSNotification(String referenceNumber, String status)
    {
        for(SMS_Notification__c notification : [SELECT  ID 
                                                FROM    SMS_Notification__c
                                                WHERE   Gateway_Reference__c = :referenceNumber AND 
                                                        Gateway_Reference__c != null])
        {
            notification.Delivered__c = Datetime.now();
            notification.Delivery_Status__c = status;
            update notification;
        }
    }
     
}